Adjust CI testing workflow
Use `gvltctl local-run` for VM test run.

diff --git a/.github/workflows/vm_build.yaml b/.github/workflows/vm_build.yaml
--- a/.github/workflows/vm_build.yaml
+++ b/.github/workflows/vm_build.yaml
@@ -102,8 +102,7 @@ jobs:
           chmod +x ./gvltctl
           ./gvltctl build \
             --containerfile Containerfile \
-            --kernel-file bin/bzImage \
-            --no-gevulot-runtime
+            --kernel-file bin/bzImage
 
       - name: Check disk.img file
         working-directory: tests/vm_builder/simple_vm
@@ -113,12 +112,32 @@ jobs:
       - name: Run test VM
         working-directory: tests/vm_builder/simple_vm
         run: |-
-          OUTPUT=$(qemu-system-x86_64 -machine q35 -nographic --hda disk.img)
-          echo "$OUTPUT"
-          RES=$(echo "$OUTPUT" | grep "Hello, world!")
-          if [[ $RES = "" ]]; then
-              echo "FAILED"
-              exit 1;
+          ./gvltctl local-run disk.img \
+            --file task.yaml \
+            --stdout \
+            --stderr \
+            --smp 1 \
+            --mem 512
+          ok=true
+          echo "Checking stdout..."
+          res=$(grep "Hello, world!" < ./output/stdout)
+          if [[ $res = "" ]]; then
+            echo "FAILED"
+            ok=false
           else
-              echo "OK"
+            echo "OK"
+          fi
+          echo "Checking output file..."
+          res=$(grep "This is output." < ./output/output.txt)
+          if [[ $res = "" ]]; then
+            echo "FAILED"
+            ok=false
+          else
+            echo "OK"
+          fi
+          if [ "$ok" = true ]; then
+            echo "Tests passed"
+          else
+            echo "Tests failed"
+            exit 1;
           fi
